name: ascii_chart
description: Plots in the console
version: 1.0.0
repository: https://github.com/rave98/ascii_chart

environment:
  sdk: ^3.5.3

dependencies:

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
